# Generated by Django 6.1.1 on 2026-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatuser_is_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='matched_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
