# Generated by Django 6.1.1 on 2026-09-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatuser_matched_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
