# Generated by Django 6.1.1 on 2026-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
