# Generated by Django 6.1.1 on 2026-09-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
