# Generated by Django 6.1.1 on 2026-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_mobilesignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='connection_count',
            field=models.IntegerField(default=0),
        ),
    ]
